"""second

Revision ID: dac92c4b85a0
Revises: 12dba9ce674f
Create Date: 2022-02-24 10:59:07.917679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dac92c4b85a0'
down_revision = '12dba9ce674f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
